//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHistory
    {
        public int GameHistoryId { get; set; }
        public int GameGroupId { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public string IpAddress { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
