//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameVariant
    {
        public short X1 { get; set; }
        public short Y1 { get; set; }
        public short X2 { get; set; }
        public short Y2 { get; set; }
        public int WordId { get; set; }
        public int GameVariantId { get; set; }
        public int GameGroupId { get; set; }
    
        public virtual GameGroup GameGroup { get; set; }
        public virtual Word Word { get; set; }
    }
}
