//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameGroups = new HashSet<GameGroup>();
            this.GameWords = new HashSet<GameWord>();
        }
    
        public int GameId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<GameGroup> GameGroups { get; set; }
        public virtual ICollection<GameWord> GameWords { get; set; }
    }
}
