//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public int WidgetId { get; set; }
        public int GameGroupId { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
