//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameGroup
    {
        public GameGroup()
        {
            this.GameVariants = new HashSet<GameVariant>();
        }
    
        public int GameGroupId { get; set; }
        public int GameId { get; set; }
        public string Level { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Language { get; set; }
        public System.Guid GameGroupId2 { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<GameVariant> GameVariants { get; set; }
    }
}
