//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using Wordament.Models;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }

        public DbSet<Game> Games { get; set; }
        public DbSet<GameGroup> GameGroups { get; set; }
        public DbSet<GameVariant> GameVariants { get; set; }
        public DbSet<GameWord> GameWords { get; set; }
        public DbSet<Word> Words { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<GameHistory> GameHistories { get; set; }
        public DbSet<DailyPuzzle> DailyPuzzles { get; set; }
        public DbSet<Widget> Widgets { get; set; }

        public virtual ObjectResult<GetRandomGame_Result> GetRandomGame(Nullable<int> nr)
        {
            var nrParameter = nr.HasValue ?
                new ObjectParameter("Nr", nr) :
                new ObjectParameter("Nr", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRandomGame_Result>("GetRandomGame", nrParameter);
        }
    }
}
