//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameWord
    {
        public int GameWordId { get; set; }
        public int GameId { get; set; }
        public int WordId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Word Word { get; set; }
    }
}
